base: &base
  adapter: mysql
  encoding: utf8
  socket: /tmp/mysql.sock
  username: root
  password:

development:
  database: crc_development
  <<: *base

test:
  database: crc_test
  <<: *base

production: 
  database: crc_production
  <<: *base